<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PGEN1FH" ignored="0" name="Test" tests="2" failures="1" timestamp="02 Mar 2018 09:10:14 GMT" time="0.05" errors="0">
  <testcase name="Dummy_test_to_fail" time="0.011" classname="test.test">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at test.test.Dummy_test_to_fail(test.java:15)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Dummy_test_to_fail -->
  <testcase name="Dummy_test_to_pass" time="0.0" classname="test.test"/>
</testsuite> <!-- Test -->
